
CREATE TABLE MANFACTURER_DETAILS(
   MFG_ID VARCHAR (15) PRIMARY KEY,
   MFG_NAME VARCHAR (100) ,
   MFG_PHONE_NO VARCHAR (14) ,
   MFG_EMAIL VARCHAR (25),
   MFG_ADDRESS VARCHAR (350) ,
   MFG_ZIPCODE VARCHAR (10) ,
   MFG_VEHICLE_TYPES VARCHAR (250) ,
   CREATED_ON TIMESTAMP NOT NULL
);




CREATE TABLE CONSUMER_DETAILS(
   CNSMR_ID VARCHAR (15) serial PRIMARY KEY,
   CNSMR_NAME VARCHAR (100) ,
   CNSMR_PHONE_NO VARCHAR (14) ,
   CNSMR_EMAIL VARCHAR (25),
   CNSMR_ADDRESS VARCHAR (350) ,
   CNSMR_ZIPCODE VARCHAR (10) ,
   CNSMR_HOLDING_VEHICLE_TYPES VARCHAR (250) ,
   CREATED_ON TIMESTAMP NOT NULL
);


CREATE TABLE SUPPLIER_DETAILS(
   CNSMR_ID VARCHAR (15) serial PRIMARY KEY,
   CNSMR_NAME VARCHAR (100) ,
   CNSMR_PHONE_NO VARCHAR (14) ,
   CNSMR_EMAIL VARCHAR (25),
   CNSMR_ADDRESS VARCHAR (350) ,
   CNSMR_ZIPCODE VARCHAR (10) ,
   CNSMR_HOLDING_VEHICLE_TYPES VARCHAR (250) ,
   CREATED_ON TIMESTAMP NOT NULL
);
